# Generated by Django 5.1.3 on 2024-11-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nombre', models.CharField(max_length=100)),
                ('_fecha', models.DateTimeField()),
                ('_lugar', models.CharField(max_length=200)),
                ('_artista', models.CharField(max_length=100)),
                ('_duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('tipo_evento', models.CharField(default='Concierto', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nombre', models.CharField(max_length=100)),
                ('_fecha', models.DateTimeField()),
                ('_lugar', models.CharField(max_length=200)),
                ('_tema', models.CharField(max_length=200)),
                ('_orador', models.CharField(max_length=100)),
                ('tipo_evento', models.CharField(default='Conferencia', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
